#!/usr/bin/env python3
"""Regenerate the Gitmoji rules from the list gitmoji publishes.

    $ script/gitmoji.py            # fetches gitmojis.json
    $ script/gitmoji.py path.json  # reads a local copy

The list is the specification's own: "an emoji from the list", in either
the unicode or the :shortcode: form. An emoji that ends in a variation
selector (U+FE0F) is accepted with or without it, since terminals and
tools disagree about keeping it.
"""
import json
import pathlib
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/carloscuesta/gitmoji/master/packages/gitmojis/src/gitmojis.json"
ROOT = pathlib.Path(__file__).resolve().parent.parent / "Commits" / "styles" / "Gitmoji"

INTENTION = """# "intention: The intention you want to express with the commit, using an
# emoji from the list. Either in the :shortcode: or unicode format." The
# list is gitmoji's own, {count} entries, generated by script/gitmoji.py; a
# subject that opens with anything else, or with an emoji and no space, is
# reported by its first word.
extends: existence
message: "Begin with a gitmoji, as the emoji or its ':shortcode:', then a space. '%s' is not one."
link: https://gitmoji.dev/specification
level: error
scope: subject
nonword: true
raw:
  - '^(?!(?:{alternation})\\x{{FE0F}}?\\s)\\S+'
"""

MESSAGE = """# "<intention> [scope?][:?] <message>": the message is "a brief explanation
# of the change", and it is not optional. Generated by script/gitmoji.py.
extends: existence
message: "A message follows the intention: what the change does."
link: https://gitmoji.dev/specification
level: error
scope: subject
nonword: true
raw:
  - '^(?:{alternation})\\x{{FE0F}}?\\s*(?:\\([^()]*\\))?:?\\s*$'
"""


def main():
    if len(sys.argv) > 1:
        data = json.loads(pathlib.Path(sys.argv[1]).read_text())
    else:
        with urllib.request.urlopen(URL) as r:
            data = json.load(r)
    entries = data["gitmojis"]

    parts = []
    for e in entries:
        parts.append(e["emoji"].rstrip("️"))
        parts.append(e["code"])
    alternation = "|".join(parts)

    for name, body in (
        ("Intention.yml", INTENTION.format(count=len(entries), alternation=alternation)),
        ("Message.yml", MESSAGE.format(alternation=alternation)),
    ):
        path = ROOT / name
        # The rule carries its cases in a `tests:` block; regenerating the
        # pattern keeps them.
        tests = ""
        if path.exists() and "\ntests:\n" in path.read_text():
            old = path.read_text()
            tests = old[old.index("\ntests:\n"):]
        path.write_text(body.rstrip("\n") + "\n" + tests)
    print(f"wrote {len(entries)} gitmojis to {ROOT}")


if __name__ == "__main__":
    main()
