#!/usr/bin/env python3
"""Generate Upstream.test.yml beside each style that mirrors a tool.

    $ script/upstream.py

Each tool keeps fixtures in its own test suite: messages, and what its rules
say about them. This reads those fixtures at a pinned commit, maps the tool's
rule to the rule here, and writes cases `vale test` runs, so the styles pass
and fail the messages the tools' own tests do. A case asserts with `contains`
or `absent`, since the messages differ and the verdict is what is shared.

A fixture that needs what a rule cannot see -- an author, a diff, a tool's
in-message directive, or a per-case config -- is left out, and the header of
each file says so.
"""
import ast
import json
import pathlib
import re
import subprocess
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent / "Commits" / "styles"

PINS = {
    "commitlint": ("conventional-changelog/commitlint", "f4b108182e6d20eca52433135c7ba1675746318e"),
    "gitlint": ("jorisroovers/gitlint", "4d9119760056492eabc201bfad5de2f9e660b85f"),
    "commitizen": ("commitizen-tools/commitizen", "9432748e110b4b678a32bb9dd3f5e24e86f1a052"),
    "conform": ("siderolabs/conform", "b951e4415e9cde1cc0cda7ad3eb467e195d8eb77"),
    "committed": ("crate-ci/committed", "e5599f97c0529434e2072e7a420a52596b621543"),
}


def fetch(tool, path):
    repo, sha = PINS[tool]
    with urllib.request.urlopen(f"https://raw.githubusercontent.com/{repo}/{sha}/{path}") as r:
        return r.read().decode("utf-8")


def scalar(key, text, indent=2):
    """A YAML value for a message: a literal block when one reads back
    exactly, otherwise a quoted string."""
    pad = " " * indent
    lines = text.split("\n")
    safe = (not lines[0][:1].isspace()) and all(not l.endswith((" ", "\t")) for l in lines) and "\t" not in text
    if safe and text.strip():
        body = text.rstrip("\n")
        return f"{pad}{key}: |\n" + "".join(f"{pad}  {l}\n" if l else "\n" for l in body.split("\n"))
    return f"{pad}{key}: {json.dumps(text, ensure_ascii=False)}\n"


def case(name, about, fmt, text, contains=None, absent=None, want=None):
    out = f"- name: {name}\n  about: {json.dumps(about)}\n  format: {fmt}\n" + scalar("input", text)
    if contains:
        out += f"  contains: {json.dumps(contains)}\n"
    if absent:
        out += "  absent:\n" + "".join(f"    - {json.dumps(a)}\n" for a in absent)
    if want is not None:
        out += f"  want: {json.dumps(want)}\n"
    return out


def write(style, tool, source, note, cases):
    repo, sha = PINS[tool]
    header = (f"# Generated by script/upstream.py from {tool}'s own test fixtures:\n"
              f"# https://github.com/{repo}/blob/{sha[:12]}/{source}\n"
              f"# {note}\n")
    (ROOT / style / "Upstream.test.yml").write_text(header + "\n" + "\n".join(cases))
    print(f"{style}: {len(cases)} cases")


# --- commitlint: config-conventional's own suite -------------------------------

COMMITLINT_RULES = {
    "typeEnum": "Commitlint.Type", "typeCase": "Commitlint.TypeCase", "typeEmpty": "Conventional.Type",
    "subjectCase": "Commitlint.SubjectCase", "subjectEmpty": "Conventional.Description",
    "subjectFullStop": "Commitlint.FullStop", "headerMaxLength": "Commitlint.HeaderLength",
    "footerLeadingBlank": "Conventional.Footer", "footerMaxLineLength": "Commitlint.FooterLength",
    "bodyLeadingBlank": "Commits.Blank", "bodyMaxLineLength": "Commitlint.BodyLength",
}
# commitlint reports a second, derived error that the rules here fold into
# the first: a capitalized type is not also "not in the list", and an empty
# subject after `fix:` is not also a missing type.
COMMITLINT_DIVERGE = {("invalidTypeCase", "typeEnum"), ("invalidSubjectEmpty", "typeEmpty")}


def commitlint():
    src = fetch("commitlint", "@commitlint/config-conventional/src/index.test.ts")
    block = re.search(r"const messages = (\{.*?\n\});", src, re.S).group(1)
    messages = json.loads(subprocess.check_output(["node", "-e", f"console.log(JSON.stringify({block}))"]))
    cases = []
    for name, body in re.findall(r'test\("([^"]+)", async \(\) => \{(.*?)\n\}\);', src, re.S):
        keys = re.findall(r"messages\.(\w+)", body)
        expected = re.findall(r"(?:errors|warnings)\.(\w+)", body)
        for key in dict.fromkeys(keys):
            inputs = messages[key] if isinstance(messages[key], list) else [messages[key]]
            for i, text in enumerate(inputs):
                suffix = f"-{i + 1}" if len(inputs) > 1 else ""
                if not expected:
                    cases.append(case(f"{name}{suffix}".replace(" ", "-"), f"'{key}': valid in commitlint", "Commitlint", text, want=""))
                for rule in dict.fromkeys(expected):
                    if (key, rule) in COMMITLINT_DIVERGE:
                        continue
                    cases.append(case(f"{name}{suffix}-{rule}", f"'{key}': commitlint reports {rule}", "Commitlint", text, contains=COMMITLINT_RULES[rule]))
    write("Commitlint", "commitlint", "@commitlint/config-conventional/src/index.test.ts",
          "Left out: the second error commitlint derives from a capitalized type or an empty subject; here that is one alert.", cases)


# --- gitlint: the sample messages ----------------------------------------------

GITLINT_RULES = {
    "T1": "Gitlint.TitleMaxLength", "T2": "Commits.Whitespace", "T3": "Gitlint.TitleTrailingPunctuation",
    "T4": "Gitlint.HardTab", "T5": "Gitlint.TitleMustNotContainWord", "T6": "Commits.Whitespace",
    "T8": "Gitlint.TitleMinLength", "B1": "Gitlint.BodyMaxLineLength", "B2": "Gitlint.BodyTrailingWhitespace",
    "B3": "Gitlint.HardTab", "B4": "Commits.Blank", "B5": "Gitlint.BodyMinLength", "B6": "Gitlint.BodyIsMissing",
}


def gitlint():
    tests = fetch("gitlint", "gitlint-core/gitlint/tests/test_lint.py")
    cases = []
    for n in (1, 2, 3):
        text = fetch("gitlint", f"gitlint-core/gitlint/tests/samples/commit_message/sample{n}")
        body = re.search(rf"def test_lint_sample{n}\(self\):(.*?)(?=\n    def )", tests, re.S).group(1)
        ids = dict.fromkeys(re.findall(r'RuleViolation\("(\w+)"', body))
        for rule in dict.fromkeys(GITLINT_RULES[i] for i in ids):
            cases.append(case(f"sample{n}-{rule.split('.')[-1]}", f"sample{n}: gitlint reports {', '.join(i for i in ids if GITLINT_RULES[i] == rule)}", "Gitlint", text, contains=rule))
    text = fetch("gitlint", "gitlint-core/gitlint/tests/samples/commit_message/no-violations")
    cases.append(case("no-violations", "no-violations: clean in gitlint", "Gitlint", text, want=""))
    write("Gitlint", "gitlint", "gitlint-core/gitlint/tests/test_lint.py",
          "Left out: sample4 and sample5, which carry gitlint's in-message `gitlint-ignore` directives, and M1, which reads the author.", cases)


# --- commitizen: cz check's parametrized messages ------------------------------

def commitizen():
    src = fetch("commitizen", "tests/commands/test_check_command.py")
    tree = ast.parse(src)
    lists = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name in ("test_check_no_conventional_commit", "test_check_conventional_commit"):
            for dec in node.decorator_list:
                if isinstance(dec, ast.Call) and dec.args and isinstance(dec.args[1], ast.List):
                    lists[node.name] = ast.literal_eval(dec.args[1])
    valid = lists["test_check_conventional_commit"] + ["fix(scope): some commit message"]
    invalid = lists["test_check_no_conventional_commit"] + ["bad commit"]
    m = re.search(r'return_value = \(\n((?:\s+"[^"\n]*"\n)+)\s+\)\n\s+util\.run_cli\("check"', src)
    if m:
        valid.append("".join(json.loads(l.strip()) for l in m.group(1).strip().split("\n")))
    cases = []
    for i, text in enumerate(valid, 1):
        cases.append(case(f"valid-{i}", "passes cz check", "Commitizen", text, absent=["Conventional.", "Commitizen.", "Commits.Blank"]))
    for i, text in enumerate(invalid, 1):
        lines = text.split("\n")
        rule = "Commits.Blank" if len(lines) > 1 and lines[1].strip() else "Conventional.Type"
        cases.append(case(f"invalid-{i}", "fails cz check", "Commitizen", text, contains=rule))
    write("Commitizen", "commitizen", "tests/commands/test_check_command.py",
          "Left out: the empty message, which Git aborts before a hook runs, and the range and prefix options, which are the hook's.", cases)


# --- conform: the DCO table and the commits its helpers make -------------------

def conform():
    src = fetch("conform", "internal/policy/commit/commit_test.go")
    cases = []
    for i, (msg, ok) in enumerate(re.findall(r'CommitMessage:\s+"((?:[^"\\]|\\.)*)",\s*ExpectValid:\s+(true|false)', src), 1):
        text = json.loads(f'"{msg}"')
        if ok == "true":
            cases.append(case(f"dco-{i}", "conform: valid DCO", "Conform", text, absent=["Conform.DCO"]))
        else:
            cases.append(case(f"dco-{i}", "conform: no DCO", "Conform", text, contains="Conform.DCO"))
    for name, body in re.findall(r'func (create\w+)\(t \*testing\.T\) error \{(.*?)\n\}', src, re.S):
        m = re.search(r'"-m", "([^"]*)"\)', body)
        msg = m.group(1) if m else ""
        if not msg or "Regex" in name and "Invalid" in name:
            continue
        if name.startswith("createValid"):
            cases.append(case(name, "conform: a valid conventional commit", "Conventional", msg, absent=["Conventional."]))
        else:
            cases.append(case(name, "conform: an invalid conventional commit", "Conventional", msg, contains="Conventional.Type"))
    write("Conform", "conform", "internal/policy/commit/commit_test.go",
          "Left out: the empty message, the scope-regex case, which needs conform's scope list, and the range tests, which need a repository.", cases)


# --- committed: its command tests ----------------------------------------------

COMMITTED_RULES = {"Work-in-progress": "Committed.NoWip", "Fixup commits": "Committed.NoFixup", "capitalized": "Committed.SubjectCapitalized"}


def committed():
    src = fetch("committed", "crates/committed/tests/cmd.rs")
    cases = []
    for i, (msg, cfg, out) in enumerate(re.findall(r'run_committed\("([^"]*)", "([^"]*)"\)\s*\.code\(\d\)\s*\.stdout_eq\(str!\[\[r#"\n(.*?)\n"#\]\]\)', src, re.S), 1):
        if cfg or not msg:
            continue
        rule = next((r for k, r in COMMITTED_RULES.items() if k in out), None)
        if rule:
            cases.append(case(f"cmd-{i}", f"committed: {out.strip().split(': ', 1)[-1]}", "Committed", msg, contains=rule))
    write("Committed", "committed", "crates/committed/tests/cmd.rs",
          "Left out: the empty message, and the cases that set a config key per run.", cases)


if __name__ == "__main__":
    commitlint()
    gitlint()
    commitizen()
    conform()
    committed()
